spring:
  application: name:fancy_friend
  #DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.124.30.198:3306/wcw001
    username: wcw001
    password: wcw231407
  redis:
    port: 6379
    host: 112.124.30.198
    password: 123456
    database: 0
  #session的配置
  session:
    #失效时间（分钟）
    timeout: 86400
    store-type: redis
server:
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        domain: 112.124.30.198
        secure: false
        same-site: lax




